---
- name: install nopcommerce
  hosts: all
  become: yes
  tasks:
    - name: fail for unsupported os
      ansible.builtin.fail:
        msg: "This playbook is designed only for Ubuntu os"
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: install dotnet runtime
      ansible.builtin.apt:
        name: "{{package_name}}"
        update_cache: yes
        state: present
      ansible.builtin.expect:
        responses:
          Question:
            - response1
    -name: create a directory
     ansible.builtin.file:
       path: /home/ubuntu/nop
       state: directory
       mode: '0755'
    - name: download nopcommerce
      ansible.builtin.unarchive:
        src: "{{ nop_url }}"
        dest: /home/ubuntu/nop
        remote_src: yes
    -name: create a directory
     ansible.builtin.file:
       path: /home/ubuntu/bin
       state: directory
       mode: '0755'
    -name: create a directory
     ansible.builtin.file:
       path: /home/ubuntu/logs
       state: directory
       mode: '0755'
    -name: edit content of /etc/systemd/system/nopCommerce.service 
     ansible.builtin.copy:
       
      